import type { QuestionReglement } from "./types";

/**
 * Banque de questions dérivée du règlement, thème par thème.
 *
 * Chaque question a été rédigée à partir du seul texte officiel, puis relue
 * deux fois : une relecture de fidélité (la citation existe-t-elle dans le
 * règlement, prouve-t-elle la réponse, l'article annoncé est-il le bon ?) et
 * une relecture de qualité (une autre option serait-elle défendable, l'énoncé
 * est-il ambigu, l'explication ajoute-t-elle une règle ?). Les questions qui
 * n'ont pas passé les deux relectures ne figurent pas ici, ni celles dont la
 * citation n'a pas été retrouvée mot pour mot dans le document.
 *
 * Les vingt questions du diaporama destiné aux parents vivent à part, dans
 * questions-parents.ts : elles sont reprises au mot près et ne doivent pas
 * être retouchées.
 *
 * Fichier engendré ; à ne pas modifier à la main sans revérifier la citation.
 */
export const QUESTIONS_BANQUE: QuestionReglement[] = [
  {
    id: "absences-billet-arrivee",
    theme: "absences",
    question: "Absent le matin, un élève arrive au lycée à 11h. Que doit-il faire ?",
    type: "qcm",
    options: [
      "Aller chercher un billet à la vie scolaire avant d'entrer en classe",
      "Aller directement en classe : le professeur signalera son arrivée",
      "Passer à l'infirmerie, qui l'autorisera à rejoindre son cours",
      "Repartir : il ne peut en aucun cas entrer avant le lendemain",
    ],
    bonne: 0,
    explication: "Quand on a manqué le début de la journée, on ne rentre pas en classe directement. On passe d'abord à la vie scolaire chercher un billet, et cette rentrée en cours de journée reste exceptionnelle.",
    articles: [
      "4.2.1",
    ],
    citation: "Un élève absent en début de journée ne peut intégrer l’établissement qu’exceptionnellement dans la journée. Il devra aller chercher un billet à la vie scolaire avant de rentrer en classe.",
    public: "eleves",
    difficulte: "moyenne",
  },
  {
    id: "absences-prevue-rattrapage",
    theme: "absences",
    question: "Une absence prévisible est autorisée par le lycée. Qui doit veiller à ce que les cours manqués soient rattrapés ?",
    type: "qcm",
    options: [
      "La famille, sous la responsabilité de laquelle l'absence est placée",
      "Le professeur principal, qui transmet et vérifie les cours",
      "La vie scolaire, qui organise des heures de rattrapage",
      "Personne : l'élève est dispensé des cours et des évaluations manquées",
    ],
    bonne: 0,
    explication: "Une absence annoncée à l'avance n'est accordée que dans des cas vraiment exceptionnels, et c'est alors à la famille de s'assurer que les cours sont rattrapés. Les évaluations, elles, devront être passées dans les conditions fixées par l'établissement.",
    articles: [
      "4.2.2",
    ],
    citation: "Cette absence sera alors placée sous la responsabilité de la famille à qui il appartiendra de veiller à ce que les cours soient rattrapés.",
    public: "parents",
    difficulte: "moyenne",
  },
  {
    id: "absences-eps-presence",
    theme: "absences",
    question: "Un élève est déclaré inapte à l'EPS pour plusieurs semaines. Il peut rester chez lui pendant les cours d'EPS.",
    type: "vrai-faux",
    options: [
      "Vrai",
      "Faux",
    ],
    bonne: 1,
    explication: "Être inapte, même totalement, ne dispense jamais d'assister au cours d'EPS : l'élève est présent et le professeur lui prépare une activité adaptée.",
    articles: [
      "4.2.3",
    ],
    citation: "Une inaptitude est l'incapacité temporaire pour un élève de pratiquer l'EPS. Elle peut être totale ou partielle et doit faire l'objet d'une demande de la part des parents à l'infirmière et a la vie scolaire par le biais de Pronote. L'infirmière informera le professeur. Cependant, elle ne dispense en aucun cas l'élève de l'obligation d'être présent au cours d'EPS. L'enseignant établira un projet adapté pour l'élève concerné.",
    public: "eleves",
    difficulte: "moyenne",
  },
  {
    id: "entrees-sorties-collegien-regime2",
    theme: "entrees-sorties",
    question: "L'emploi du temps annuel d'un collégien commence par une permanence en H1. Peut-il arriver seulement pour son premier cours ?",
    type: "qcm",
    options: [
      "Non, aucun collégien ne peut arriver après 7h45, quel que soit son emploi du temps",
      "Oui, à condition de prévenir la vie scolaire chaque matin concerné",
      "Oui, si sa famille a choisi le régime 2 : il est alors autorisé à l'année, sous la responsabilité de ses parents",
      "Oui, mais seulement avec une demande écrite renouvelée chaque semaine",
    ],
    bonne: 2,
    explication: "Deux régimes sont proposés aux familles des collégiens. Avec le second, un élève qui a une permanence en début ou en fin de journée toute l'année peut arriver pour son premier vrai cours ou partir après son dernier, sous la responsabilité de ses parents, sans démarche à refaire.",
    articles: [
      "2.6",
      "2.6.1",
    ],
    citation: "Régime 2 : si son emploi du temps annuel comporte une heure de permanence en H1 ou en H7, l’élève est autorisé à l’année, sous la responsabilité de ses parents, à arriver pour sa première heure de cours effective ou à partir à la fin de la dernière heure effective de cours",
    public: "les-deux",
    difficulte: "moyenne",
  },
  {
    id: "entrees-sorties-permanence-option",
    theme: "entrees-sorties",
    question: "Les parents d'un lycéen ont signé l'autorisation de sortie en début d'année. Il veut sortir pendant sa permanence de l'après-midi, avant son cours d'option. Que faut-il ?",
    type: "qcm",
    options: [
      "Rien de plus : l'autorisation signée en début d'année couvre cette sortie",
      "Une autorisation complémentaire",
      "Un billet remis le jour même par le professeur de l'option",
      "Un message des parents sur Pronote le matin même",
    ],
    bonne: 1,
    explication: "L'autorisation signée à la rentrée ne suffit pas pour sortir pendant une permanence située avant un cours d'option en fin de journée. Les parents doivent fournir une autorisation supplémentaire pour ce cas précis.",
    articles: [
      "2.6",
      "2.6.2",
    ],
    citation: "Une autorisation complémentaire sera demandée en cas de sortie durant un temps de permanence avant un cours d’option (après 12h40).",
    public: "les-deux",
    difficulte: "difficile",
  },
  {
    id: "deplacements-sonnerie-recreation",
    theme: "deplacements",
    question: "La sonnerie de la récréation retentit. Que fait l'élève ?",
    type: "qcm",
    options: [
      "Il quitte la salle et descend dans la cour ou dans un espace autorisé",
      "Il reste seul dans la salle s'il préfère réviser",
      "Il joue dans le couloir ou dans l'escalier avec ses camarades",
      "Il demande un billet à la vie scolaire avant de descendre",
    ],
    bonne: 0,
    explication: "Dès la sonnerie, la salle se vide : on descend dans la cour ou dans un espace autorisé. Rester seul dans une classe sans adulte, ou jouer dans les couloirs, les escaliers et les toilettes, n'est jamais permis.",
    articles: [
      "2.7",
    ],
    citation: "Aux sonneries de début de récréation, les élèves quittent leur salle de classe et descendent dans la cour ou dans les espaces autorisés.",
    public: "eleves",
    difficulte: "facile",
  },
  {
    id: "deplacements-jour-de-pluie",
    theme: "deplacements",
    question: "Il pleut au moment de la récréation. Où vont les élèves ?",
    type: "qcm",
    options: [
      "Ils restent seuls dans leur salle de classe",
      "Ils sont dirigés par la vie scolaire vers des espaces spécifiques",
      "Ils peuvent jouer dans les couloirs le temps de l'averse",
      "La récréation est supprimée et les cours s'enchaînent",
    ],
    bonne: 1,
    explication: "Quand il pleut, on ne reste pas en classe et on ne joue pas dans les couloirs : la vie scolaire conduit les élèves vers des espaces prévus pour cela.",
    articles: [
      "2.7",
    ],
    citation: "Aucun élève n'est autorisé à rester dans une salle de classe en dehors de la présence d'un adulte, ou à jouer dans les couloirs, escaliers ou toilettes. Toutefois en cas de pluie, les élèves seront dirigés par la vie scolaire dans des espaces spécifiques.",
    public: "eleves",
    difficulte: "moyenne",
  },
  {
    id: "deplacements-vestiaires-eps",
    theme: "deplacements",
    question: "Le cours d'EPS est terminé. Combien de temps les élèves ont-ils pour se rhabiller ?",
    type: "qcm",
    options: [
      "5 minutes",
      "10 minutes",
      "15 minutes",
      "Tout l'interclasse, sans durée fixée",
    ],
    bonne: 1,
    explication: "Les vestiaires servent à s'habiller et se déshabiller : 5 minutes au début du cours pour se mettre en tenue, 10 minutes à la fin pour se rhabiller.",
    articles: [
      "2.7",
    ],
    citation: "Avant et après les cours d'EPS, les vestiaires sont le lieu d'habillage et de déshabillage. Les élèves disposent de 5 minutes en début des cours pour se mettre en tenue et 10 minutes en fin des cours pour se rhabiller. L'accès aux vestiaires est interdit pendant la séance d'EPS.",
    public: "eleves",
    difficulte: "difficile",
  },
  {
    id: "deplacements-toilettes-batiment-b",
    theme: "deplacements",
    question: "Un cours du collège a lieu au Bâtiment B. L'élève peut utiliser les toilettes de ce bâtiment.",
    type: "vrai-faux",
    options: [
      "Vrai",
      "Faux",
    ],
    bonne: 1,
    explication: "Même quand le cours se déroule au Bâtiment B, les collégiens et les lycéens n'utilisent jamais les toilettes de ce bâtiment.",
    articles: [
      "2.7",
    ],
    citation: "Lorsque les cours du second degré se déroulent au Bâtiment B, en aucun cas les collégiens et lycéens ne doivent utiliser les toilettes du bâtiment B",
    public: "eleves",
    difficulte: "difficile",
  },
  {
    id: "transport-monter-des-la-fin-des-cours",
    theme: "transport",
    question: "Le soir, Rami, inscrit au bus, reste discuter dans la cour après son dernier cours et monte au dernier moment. Il respecte le règlement.",
    type: "vrai-faux",
    options: [
      "Vrai",
      "Faux",
    ],
    bonne: 1,
    explication: "Dès la fin des cours, les élèves inscrits doivent monter dans le bus et y rester jusqu'au départ. On n'attend pas ailleurs dans l'établissement.",
    articles: [
      "2.8",
    ],
    citation: "Afin de ne pas retarder le départ des transports scolaires, les familles doivent veiller à amener leurs enfants à l'heure au point de départ. Le soir, les élèves doivent monter et rester dans le bus dès la fin de leurs cours.",
    public: "eleves",
    difficulte: "moyenne",
  },
  {
    id: "transport-manquement-radiation",
    theme: "transport",
    question: "Un élève chahute régulièrement dans le bus et refuse d'écouter l'accompagnateur. Que risque-t-il ?",
    type: "qcm",
    options: [
      "Rien : le règlement intérieur ne s'applique pas dans le bus",
      "Uniquement un rappel à l'ordre du chauffeur",
      "Des punitions ou des sanctions, et jusqu'à la radiation du service de transport",
      "Une amende que sa famille verse au transporteur",
    ],
    bonne: 2,
    explication: "Dans le bus, les règles de l'établissement s'appliquent et il faut suivre les consignes des accompagnateurs et des chauffeurs. En cas de manquement, un élève peut être puni ou sanctionné, et même perdre le droit d'utiliser le bus, temporairement ou définitivement.",
    articles: [
      "2.8",
    ],
    citation: "Les manquements à ces règles, pourront entraîner punitions, sanctions, voire une radiation temporaire ou définitive du service des transports.",
    public: "eleves",
    difficulte: "moyenne",
  },
  {
    id: "telephone-depot-arrivee",
    theme: "telephone",
    question: "Un élève arrive au lycée le matin avec son téléphone dans son sac. Que doit-il en faire ?",
    type: "qcm",
    options: [
      "L’éteindre et le déposer dans une boîte sécurisée prévue à cet effet",
      "Le mettre en silencieux et le garder au fond de son sac",
      "Le remettre à son professeur principal au début du premier cours",
      "Le garder sur lui, du moment qu’il ne s’en sert pas",
    ],
    bonne: 0,
    explication: "Le téléphone ne se range pas simplement dans le sac : à l’arrivée, on l’éteint et on le dépose dans la boîte sécurisée, selon l’organisation mise en place par la vie scolaire.",
    articles: [
      "4.7.1",
    ],
    citation: "À leur arrivée, les élèves doivent impérativement éteindre leur téléphone et le déposer dans les boîtes sécurisées prévues, selon l’organisation de la vie scolaire.",
    public: "eleves",
    difficulte: "facile",
  },
  {
    id: "telephone-refus-presenter",
    theme: "telephone",
    question: "Soupçonnant un usage interdit, la CPE demande à un élève de lui présenter son téléphone. L’élève refuse. Que prévoit le règlement ?",
    type: "qcm",
    options: [
      "Ce refus peut entraîner une mesure éducative ou disciplinaire",
      "Rien : l’élève est dans son droit, le refus est sans conséquence",
      "L’adulte fouille alors le sac et consulte le contenu de l’appareil",
      "L’élève reçoit automatiquement la note de 0/20 au prochain contrôle",
    ],
    bonne: 0,
    explication: "Un adulte peut demander à voir l’appareil ; il ne fouille pas et ne regarde pas ce qu’il contient sans accord. En revanche, refuser de le présenter peut valoir une mesure éducative ou disciplinaire.",
    articles: [
      "4.7.3",
    ],
    citation: "4.7.3 Contrôle du téléphone en cas de suspicion En cas de suspicion d’usage non conforme, l’élève pourra être invité à présenter son appareil à un membre de l’équipe éducative ou de direction. L’établissement ne procède à aucune fouille ni consultation du contenu sans l’accord de l’élève et, le cas échéant, de ses représentants légaux. Tout refus de se soumettre à cette demande est susceptible d’entraîner une mesure éducative ou disciplinaire.",
    public: "eleves",
    difficulte: "difficile",
  },
  {
    id: "telephone-responsabilite-boite",
    theme: "telephone",
    question: "Le téléphone d’un élève disparaît de la boîte de rangement collectif. Puisque c’est l’établissement qui fournit la boîte, il est responsable de l’appareil.",
    type: "vrai-faux",
    options: [
      "Vrai",
      "Faux",
    ],
    bonne: 1,
    explication: "Le lycée met les rangements à disposition, mais chacun reste responsable de ses propres affaires : le téléphone déposé demeure sous la responsabilité de son propriétaire.",
    articles: [
      "4.7.4",
    ],
    citation: "4.7.4 Responsabilité L’établissement met à disposition des dispositifs de rangement collectif. Toutefois, chaque élève demeure responsable de son matériel personnel.",
    public: "les-deux",
    difficulte: "moyenne",
  },
  {
    id: "images-ia-qui-autorise",
    theme: "images-ia",
    question: "Un élève veut filmer un moment de la vie du lycée pour le compte Instagram de sa classe. À qui doit-il demander l'autorisation ?",
    type: "qcm",
    options: [
      "À la direction",
      "Au bureau de la vie scolaire",
      "À son professeur principal",
      "Aux délégués de sa classe",
    ],
    bonne: 0,
    explication: "On ne filme pas, on ne photographie pas et on n'enregistre pas dans l'établissement sans avoir obtenu l'accord explicite de la direction. Aucun autre accord ne remplace celui-là.",
    articles: [
      "4.7.2",
    ],
    citation: "4.7.2 Interdiction des enregistrements et captations Il est strictement interdit d’enregistrer des conversations, de capter des images, de réaliser des photos, vidéos ou tout autre enregistrement sonore ou visuel dans l’établissement sans autorisation expresse de la direction. Cette interdiction concerne toute la communauté scolaire et vise à garantir le respect de la vie privée, de la dignité et de l’image de chacun. La diffusion, le partage ou la modification de ces contenus, par quelque moyen que ce soit, est également interdite.",
    public: "eleves",
    difficulte: "moyenne",
  },
  {
    id: "images-ia-charte",
    theme: "images-ia",
    question: "Un élève demande où sont écrites les règles d'utilisation de l'intelligence artificielle. Que lui répond-on ?",
    type: "qcm",
    options: [
      "Dans une charte annexée au règlement, qui a la même valeur que lui",
      "Dans une charte annexée, mais qui n'a qu'une valeur de conseil",
      "Nulle part : le règlement ne dit rien de l'intelligence artificielle",
      "Dans le carnet de vie scolaire remis à la rentrée",
    ],
    bonne: 0,
    explication: "Une charte particulière, jointe au règlement intérieur, encadre l'usage de l'intelligence artificielle. Elle s'impose exactement comme le règlement lui-même.",
    articles: [
      "4.7.2",
    ],
    citation: "Les usages liés à l’intelligence artificielle sont encadrés par une charte spécifique annexée au présent règlement ayant la même valeur que le présent règlement.",
    public: "les-deux",
    difficulte: "difficile",
  },
  {
    id: "tenue-oubli-eps",
    theme: "tenue",
    question: "Un élève se présente au cours d'EPS sans sa tenue de sport. Que se passe-t-il ?",
    type: "qcm",
    options: [
      "Il participe en vêtements de ville si le professeur l'accepte",
      "Le professeur lui prête une tenue de l'établissement pour la séance",
      "On demande à ses parents d'apporter la tenue ; il ne participe pas et est noté absent",
      "Il est dispensé pour la séance, sans aucune conséquence",
    ],
    bonne: 2,
    explication: "Sans la tenue de sport de l'établissement, on appelle les parents pour qu'ils l'apportent. En attendant, l'élève ne pratique pas, il est compté absent et cette absence n'est pas excusée : elle peut donc être sanctionnée.",
    articles: [
      "4.4",
    ],
    citation: "En cours d’EPS, la tenue sportive de l’établissement est obligatoire pour tous les élèves. En cas d’oubli, il sera demandé aux parents d’apporter la tenue à leur enfant. L’élève ne pourra pas participer à l’activité. L’élève sera noté absent et le motif considéré irrecevable. L’élève s’exposera donc à des sanctions.",
    public: "les-deux",
    difficulte: "moyenne",
  },
  {
    id: "tenue-inaptitude-demarche",
    theme: "tenue",
    question: "Un élève ne peut pas pratiquer l'EPS pendant deux semaines. Quelle démarche ses parents doivent-ils faire ?",
    type: "qcm",
    options: [
      "Adresser une demande à l'infirmière et à la vie scolaire via Pronote",
      "Remettre le certificat médical directement au professeur d'EPS",
      "Envoyer un courriel au professeur principal",
      "Faire signer le carnet de vie scolaire par le médecin de famille",
    ],
    bonne: 0,
    explication: "La demande d'inaptitude passe par les parents, sur Pronote, auprès de l'infirmière et de la vie scolaire. C'est ensuite l'infirmière qui prévient le professeur : l'élève n'a pas à faire la démarche lui-même auprès de son enseignant.",
    articles: [
      "4.2.3",
    ],
    citation: "4.2.3. Inaptitude à la pratique d’une activité physique et absences en EPS Une inaptitude est l’incapacité temporaire pour un élève de pratiquer l’EPS. Elle peut être totale ou partielle et doit faire l’objet d’une demande de la part des parents à l’infirmière et a la vie scolaire par le biais de Pronote. L’infirmière informera le professeur. Cependant, elle ne dispense en aucun cas l'élève de l'obligation d'être présent au cours d'EPS. L’enseignant établira un projet adapté pour l’élève concerné. L’établissement se réserve le droit de demander l’expertise du médecin scolaire pour toute inaptitude prononcée par un professionnel extérieur.",
    public: "parents",
    difficulte: "moyenne",
  },
  {
    id: "tenue-bijoux-chaussures-eps",
    theme: "tenue",
    question: "Avant l'EPS, un élève garde sa montre et sa chaîne de cou, et enfile des baskets sans lacets ni velcro. Que dit le règlement ?",
    type: "qcm",
    options: [
      "Il peut garder ses bijoux s'ils ne gênent pas ses mouvements",
      "Il doit ôter montre et chaîne, et porter des chaussures serrées par des lacets ou des velcro",
      "Seules les chaussures posent problème, les bijoux sont tolérés",
      "Le professeur décide au cas par cas selon l'activité",
    ],
    bonne: 1,
    explication: "Pour faire du sport en sécurité, les chaussures doivent tenir au pied avec des lacets ou des velcro, et tous les bijoux (montre, chaîne, piercing) doivent être enlevés avant la séance.",
    articles: [
      "4.4",
    ],
    citation: "Pour des raisons de sécurité liées à la pratique du sport, les chaussures de sport doivent impérativement être serrées par des lacets ou des «velcro». De même, les bijoux, montres, chaînes de cou, piercings, etc., doivent être ôtés.",
    public: "eleves",
    difficulte: "difficile",
  },
  {
    id: "tenue-inaptitude-presence",
    theme: "tenue",
    question: "Un élève déclaré inapte en EPS peut rester en permanence pendant l'heure de sport.",
    type: "vrai-faux",
    options: [
      "Vrai",
      "Faux",
    ],
    bonne: 1,
    explication: "Une inaptitude dispense de pratiquer, pas d'assister au cours : l'élève vient en EPS comme les autres et le professeur lui prépare un travail adapté.",
    articles: [
      "4.2.3",
    ],
    citation: "Une inaptitude est l’incapacité temporaire pour un élève de pratiquer l’EPS. Elle peut être totale ou partielle et doit faire l’objet d’une demande de la part des parents à l’infirmière et a la vie scolaire par le biais de Pronote. L’infirmière informera le professeur. Cependant, elle ne dispense en aucun cas l'élève de l'obligation d'être présent au cours d'EPS. L’enseignant établira un projet adapté pour l’élève concerné.",
    public: "eleves",
    difficulte: "moyenne",
  },
  {
    id: "comportement-jeux-de-balle",
    theme: "comportement",
    question: "Des élèves veulent jouer au ballon pendant la récréation. Que doivent-ils faire ?",
    type: "qcm",
    options: [
      "Jouer dans les zones sportives de la cour, après autorisation de la vie scolaire",
      "Jouer partout dans la cour : la récréation est un temps libre",
      "Demander l'accord du professeur de l'heure précédente",
      "Jouer dans les couloirs si la cour est trop occupée",
    ],
    bonne: 0,
    explication: "Le ballon, c'est seulement pendant les récréations, seulement dans les zones sportives de la cour, et seulement si la vie scolaire a donné son accord. Les balles dures venues de la maison, elles, n'entrent pas dans l'établissement.",
    articles: [
      "4.5",
    ],
    citation: "Les jeux de balle sont limités aux temps des récréations et ne peuvent avoir lieu que dans les zones sportives de la cour et sur autorisation de la vie scolaire. Il est interdit aux élèves d'apporter des balles dures dans l'établissement. Si nécessaire, elles leur seront fournies dans le contexte d'activités encadrées.",
    public: "eleves",
    difficulte: "moyenne",
  },
  {
    id: "comportement-manger-intemperies",
    theme: "comportement",
    question: "Il pleut très fort à la récréation. Des élèves demandent à manger leur goûter à l'intérieur. Est-ce possible ?",
    type: "qcm",
    options: [
      "Oui : une autorisation exceptionnelle peut être donnée quand les conditions météo sont difficiles",
      "Non : aucune exception n'est prévue, quelle que soit la météo",
      "Oui : dans les couloirs et les escaliers, mais pas en salle",
      "Oui : manger en salle est libre dès qu'aucun cours n'a lieu",
    ],
    bonne: 0,
    explication: "En temps normal, on ne mange pas dans les salles de classe, les salles d'étude, le CCC, le gymnase, ni dans les couloirs et les escaliers. Quand la météo empêche de sortir, un adulte peut donner une autorisation exceptionnelle : elle n'est jamais automatique.",
    articles: [
      "4.5",
    ],
    citation: "Il est strictement interdit de manger dans les espaces à vocation pédagogique (salles de classe, salles d’étude, CCC, gymnase, etc.), ainsi que dans les couloirs et escaliers pour des raisons de sécurité. Des autorisations exceptionnelles peuvent être données en cas de conditions météorologiques difficiles.",
    public: "eleves",
    difficulte: "difficile",
  },
  {
    id: "evaluations-absence-controle",
    theme: "evaluations",
    question: "Votre enfant est absent le jour d'un contrôle prévu. Que devez-vous faire ?",
    type: "qcm",
    options: [
      "Envoyer une excuse écrite via Pronote au professeur concerné et à la vie scolaire",
      "Téléphoner à l'accueil le matin même, sans écrit",
      "Prévenir uniquement le professeur principal au retour de l'élève",
      "Rien : l'absence est régularisée automatiquement par Pronote",
    ],
    bonne: 0,
    explication: "Quand tu manques une évaluation prévue, tes parents doivent envoyer une excuse écrite sur Pronote, au professeur concerné et à la vie scolaire. Le passage par la vie scolaire pour régulariser l'absence n'est jamais facultatif.",
    articles: [
      "3.1.6",
    ],
    citation: "Toute absence à une évaluation prévue doit faire l´objet d´une excuse écrite parentale via Pronote au professeur concerné et à la vie scolaire. La régularisation administrative à la vie scolaire est incontournable.",
    public: "parents",
    difficulte: "moyenne",
  },
  {
    id: "evaluations-telephone-fraude",
    theme: "evaluations",
    question: "Pendant un contrôle, un élève a son téléphone éteint au fond de son sac. Comment est-il considéré ?",
    type: "qcm",
    options: [
      "Tout va bien : le téléphone est éteint",
      "C'est toléré tant que le téléphone reste dans le sac",
      "Il est réputé fraudeur : la simple possession suffit",
      "Seules les montres connectées sont interdites en évaluation",
    ],
    bonne: 2,
    explication: "Pendant une évaluation, avoir sur soi un téléphone ou un objet connecté suffit à être considéré comme fraudeur, même s'il est éteint et rangé. Et toute fraude est sanctionnée.",
    articles: [
      "3.1.4",
    ],
    citation: "Toute fraude lors d’une évaluation sera sanctionnée. L’élève en possession d’un téléphone portable ou de tout objet connecté lors d’une évaluation est réputé fraudeur.",
    public: "eleves",
    difficulte: "facile",
  },
  {
    id: "evaluations-avertissement-conseil",
    theme: "evaluations",
    question: "Le conseil de classe estime qu'un élève doit recevoir un avertissement pour manque de travail. Qui peut le prononcer ?",
    type: "qcm",
    options: [
      "Le conseil de classe lui-même, par un vote",
      "La cheffe d'établissement ou la Proviseure déléguée, sur proposition du conseil de classe",
      "Le professeur principal, au nom de l'équipe",
      "La CPE, après un entretien avec la famille",
    ],
    bonne: 1,
    explication: "Le conseil de classe propose, mais il ne prononce pas l'avertissement lui-même : la décision revient à la cheffe d'établissement ou à la Proviseure déléguée. Si rien ne s'améliore au trimestre suivant, un blâme peut suivre.",
    articles: [
      "3.1.4",
    ],
    citation: "Un avertissement pour manque de travail, d’assiduité ou de comportement peut être attribué par la cheffe d’établissement ou la Proviseure déléguée sur proposition du conseil de classe",
    public: "les-deux",
    difficulte: "difficile",
  },
  {
    id: "evaluations-encouragement-pronote",
    theme: "evaluations",
    question: "Un élève s'investit beaucoup dans la vie du lycée. Où un professeur peut-il le valoriser au quotidien ?",
    type: "qcm",
    options: [
      "Dans la rubrique « encouragement » de Pronote",
      "Uniquement dans le carnet de vie scolaire",
      "Par un affichage sur les panneaux de la cour",
      "Nulle part : il faut attendre le conseil de classe",
    ],
    bonne: 0,
    explication: "Ton engagement peut être signalé au jour le jour sur Pronote, dans la rubrique prévue pour les encouragements. Il n'y a pas besoin d'attendre la fin de la période pour être valorisé.",
    articles: [
      "3.1.5",
    ],
    citation: "Au quotidien, l’élève peut être valorisé sur Pronote (rubrique « encouragement »).",
    public: "les-deux",
    difficulte: "moyenne",
  },
  {
    id: "sante-malaise-en-cours",
    theme: "sante",
    question: "En plein cours, un élève se sent mal. Quel est le premier réflexe prévu ?",
    type: "qcm",
    options: [
      "Il prévient son enseignant, qui l'autorise à se rendre à la vie scolaire",
      "Il sort de la salle et se rend seul directement à l'infirmerie",
      "Il envoie un message à ses parents pour qu'ils viennent le chercher",
      "Il attend la fin de l'heure et va voir l'accueil",
    ],
    bonne: 0,
    explication: "Quand tu ne te sens pas bien, tu le dis d'abord à ton professeur. C'est lui qui t'autorise à descendre à la vie scolaire, première étape avant l'infirmerie.",
    articles: [
      "3.2.1",
    ],
    citation: "3.2.1. Procédure de sortie d'un élève malade 1ère étape : Signalement et passage à l’infirmerie • L’élève ressent un malaise et en informe son enseignant. • L’enseignant autorise l’élève à se rendre à la vie scolaire. • La vie scolaire remet un billet de passage à l’élève pour l’infirmerie (lycée) ou renseigne le carnet de vie scolaire (collège).",
    public: "eleves",
    difficulte: "facile",
  },
  {
    id: "sante-billet-infirmerie",
    theme: "sante",
    question: "Un lycéen a l'autorisation d'aller à l'infirmerie. Qui lui remet le billet de passage ?",
    type: "qcm",
    options: [
      "L'infirmière, à son arrivée à l'infirmerie",
      "La vie scolaire",
      "Le professeur principal",
      "Le portier, à l'entrée de l'établissement",
    ],
    bonne: 1,
    explication: "On ne se présente pas à l'infirmerie les mains vides : c'est la vie scolaire qui remet le billet de passage aux lycéens, et qui renseigne le carnet de vie scolaire des collégiens.",
    articles: [
      "3.2",
      "3.2.1",
    ],
    citation: "La vie scolaire remet un billet de passage à l’élève pour l’infirmerie (lycée) ou renseigne le carnet de vie scolaire (collège).",
    public: "eleves",
    difficulte: "moyenne",
  },
  {
    id: "sante-sortie-taxi",
    theme: "sante",
    question: "L'infirmière et les parents conviennent que l'élève malade rentrera seul en taxi. Que faut-il en plus ?",
    type: "qcm",
    options: [
      "Rien de plus : l'accord donné au téléphone suffit",
      "Un mail d'autorisation des parents, que l'infirmière transmet à la vie scolaire",
      "Un certificat médical remis dès le lendemain",
      "L'accord écrit du professeur principal",
    ],
    bonne: 1,
    explication: "Un enfant ne quitte pas l'établissement seul sur une simple parole : les parents doivent envoyer un mail autorisant le retour en taxi, et l'infirmière le transmet à la vie scolaire.",
    articles: [
      "3.2.1",
    ],
    citation: "3ère étape : Départ de l'élève Si le départ de l'élève est décidé avec les parents : l'infirmière contacte la vie scolaire et l'accueil, pour organiser sa sortie. Les parents viennent chercher leur enfant, ou confirment qu'il peut rentrer seul en taxi. Dans ce, cas, l'infirmière demandera aux parents un mail d'autorisation d'accompagnement par taxi et transmettra à la vie scolaire. Quand les parents ou le taxi arrivent, le portier informe l'accueil, qui à son tour avertit la vie scolaire qui se charge d'appeler l'élève.",
    public: "parents",
    difficulte: "difficile",
  },
  {
    id: "discipline-exclusion-de-cours",
    theme: "discipline",
    question: "Un professeur exclut un élève de son cours. Que se passe-t-il ?",
    type: "qcm",
    options: [
      "L'élève sort seul et attend dans le couloir jusqu'à la fin de l'heure",
      "Un camarade l'accompagne à la vie scolaire et le professeur rédige immédiatement un rapport d'incident",
      "L'élève descend seul dans la cour et revient au cours suivant",
      "Le professeur note l'incident sur Pronote et prévient les parents en fin de semaine",
    ],
    bonne: 1,
    explication: "Une exclusion de cours n'est jamais une sortie libre : un camarade accompagne l'élève jusqu'à la vie scolaire, qui le prend en charge. Le professeur écrit un rapport tout de suite, transmis à la direction et aux parents.",
    articles: [
      "5.1.1",
    ],
    citation: "- exclusion ponctuelle d'un cours, justifiée par un manquement grave, elle doit demeurer tout à fait exceptionnelle. Elle donne lieu systématiquement à un rapport d’incident, établi immédiatement par le professeur, remis au service de l a vie scolaire, puis en copie à l a Cheffe d'établissement, à l a Proviseure Déléguée et aux parents. L'élève sera accompagné à la vie scolaire par un camarade pour y être pris en charge.",
    public: "eleves",
    difficulte: "moyenne",
  },
  {
    id: "discipline-commission-educative",
    theme: "discipline",
    question: "Un élève accumule des perturbations répétées mais mineures. Qui peut demander une commission éducative ?",
    type: "qcm",
    options: [
      "Uniquement la Cheffe d'établissement",
      "Les délégués de la classe, lors du conseil de classe",
      "Le professeur principal, le service de vie scolaire ou la Proviseure Déléguée",
      "Les parents, par une demande écrite sur Pronote",
    ],
    bonne: 2,
    explication: "Quand de petits manquements se répètent, la situation de l'élève est examinée ensemble par les adultes qui le suivent. La demande vient du professeur principal, de la vie scolaire ou de la Proviseure Déléguée.",
    articles: [
      "5.1.3",
    ],
    citation: "Elle est réunie sur proposition du professeur principal, du service de vie scolaire ou de la Proviseure Déléguée.",
    public: "les-deux",
    difficulte: "moyenne",
  },
  {
    id: "discipline-reinscription-apres-sanction",
    theme: "discipline",
    question: "Un élève reçoit une sanction disciplinaire en janvier. Quelle conséquence pour l'année suivante ?",
    type: "qcm",
    options: [
      "Aucune : la sanction est effacée à la fin de l'année scolaire",
      "Il devra obligatoirement redoubler sa classe",
      "Il est automatiquement exclu définitivement de l'établissement",
      "Sa réinscription pour l'année suivante est compromise",
    ],
    bonne: 3,
    explication: "Une sanction ne s'arrête pas à la fin de l'année : elle met en jeu le retour dans l'établissement l'année suivante, qui n'est alors plus automatique.",
    articles: [
      "5.1.2",
    ],
    citation: "À tout moment de l'année, si un élève a été sanctionné, la réinscription pour l’année scolaire suivante sera compromise. La Cheffe d’établissement informera la famille suffisamment tôt de la non réinscription de l’élève afin que cette dernière puisse prendre les dispositions nécessaires pour une scolarisation dans un autre établissement. Elle peut être accordée, à titre exceptionnel, suite à un entretien entre la Cheffe d’établissement, la Proviseure Déléguée, la famille et l’élève.",
    public: "les-deux",
    difficulte: "moyenne",
  },
  {
    id: "droits-conseil-de-classe",
    theme: "droits",
    question: "Le conseil de classe se réunit. Qu'en est-il des représentants des élèves ?",
    type: "qcm",
    options: [
      "Ils participent aux travaux du conseil de classe",
      "Ils n'y assistent pas : le conseil est réservé aux adultes",
      "Ils y sont remplacés par les parents délégués",
      "Ils n'y siègent qu'au lycée, jamais au collège",
    ],
    bonne: 0,
    explication: "Les représentants des élèves prennent part aux travaux du conseil de classe, comme aux autres instances où ils siègent, notamment les conseils de vie collégienne et lycéenne.",
    articles: [
      "1.2",
    ],
    citation: "1.2. Le droit à l'exercice de la citoyenneté (droit d'être représenté) Les élèves sont représentés par des délégués, qui bénéficient d'une formation et sont les interlocuteurs privilégiés de l'équipe éducative et de l'administration. Plus généralement, les représentants des élèves participent aux travaux des conseils de classe et aux différentes instances dans lesquelles ils siègent, en particulier le Conseil de Vie Collégienne (CVC O) et le Conseil de Vie Lycéenne (CVL).",
    public: "les-deux",
    difficulte: "moyenne",
  },
  {
    id: "droits-affichage-panneaux",
    theme: "droits",
    question: "Des élèves ont préparé une affiche pour annoncer leur projet. Comment l'afficher ?",
    type: "qcm",
    options: [
      "Sur les panneaux prévus à cet effet, sans anonymat, sous le contrôle de la Proviseure Déléguée",
      "Sur le mur de leur choix, du moment que l'affiche est signée",
      "Sans signature, pour éviter les ennuis",
      "Uniquement après un vote de la classe en heure de vie de classe",
    ],
    bonne: 0,
    explication: "Une affiche se pose sur les panneaux réservés à l'affichage, et jamais sans nom : on doit savoir qui l'a écrite. C'est la Proviseure Déléguée, ou la personne qu'elle désigne, qui en assure le contrôle.",
    articles: [
      "1.3",
    ],
    citation: "Tout affichage est assuré, sous le contrôle de la Proviseure Déléguée ou de son représentant, sur les panneaux prévus à cet effet et ne peut être anonyme.",
    public: "eleves",
    difficulte: "difficile",
  },
  {
    id: "communication-identifiants-pronote",
    theme: "communication",
    question: "Un élève demande à ses parents leurs identifiants Pronote pour suivre lui-même ses notes. Que prévoit le règlement ?",
    type: "qcm",
    options: [
      "Les parents peuvent les lui donner à partir de la seconde",
      "Chaque famille reçoit un identifiant unique, partagé entre les parents et l'enfant",
      "Les identifiants appartiennent aux parents et valent signature : il leur est vivement recommandé de ne pas les transmettre",
      "Les parents doivent les communiquer au professeur principal en début d'année",
    ],
    bonne: 2,
    explication: "Le compte Pronote des parents leur est personnel : s'en servir revient à signer. C'est pourquoi on leur recommande vivement de ne pas donner leurs codes à leur enfant.",
    articles: [
      "3.1.1",
    ],
    citation: "Le carnet de correspondance est dématérialisé sur Pronote. Les observations et encouragements des enseignants y sont notifiés. Les parents doivent consulter Pronote quotidiennement. Pour cela, ils disposent d'identifiants qui leurs sont propres et valent signature. Il leur est vivement recommandé de ne pas les transmettre à leurs enfants.",
    public: "parents",
    difficulte: "moyenne",
  },
  {
    id: "communication-carnet-vie-scolaire",
    theme: "communication",
    question: "En cours, un collégien a un comportement inapproprié : un adulte lui prend son carnet de vie scolaire. Que va-t-il se passer ?",
    type: "qcm",
    options: [
      "Le carnet reste à la vie scolaire jusqu'à la fin du trimestre",
      "Une observation sera ensuite portée sur Pronote",
      "Les parents devront venir récupérer le carnet eux-mêmes à l'accueil",
      "Un nouveau carnet sera racheté aux frais de la famille",
    ],
    bonne: 1,
    explication: "Le carnet de vie scolaire peut être pris à tout moment par un adulte de l'établissement quand le comportement n'est pas correct. Il sert alors à inscrire une observation sur Pronote, que la famille verra.",
    articles: [
      "3.1.1",
    ],
    citation: "A la rentrée, les collégiens auront un carnet de vie scolaire qu'ils devront avoir avec eux à chaque cours. Dans ce carnet, « passeport de l'élève dans l'établissement », devra être signé par lui et ses parents. Le calendrier annuel et son emploi du temps y seront portés. À tout moment il pourra être saisi par un adulte de l'établissement en cas de comportement inapproprié, afin de pouvoir mettre ensuite une observation sur Pronote. Il sera aussi utilisé lors des passages à l'infirmerie et pour les billets de retard.",
    public: "eleves",
    difficulte: "moyenne",
  },
  {
    id: "communication-pap-bilan",
    theme: "communication",
    question: "Des parents pensent que leur enfant a un trouble des apprentissages et demandent un accompagnement personnalisé (PAP). Que faut-il fournir ?",
    type: "qcm",
    options: [
      "Une simple demande écrite des parents au professeur principal",
      "Une décision de la CPE après une période d'observation en classe",
      "Un avis favorable du conseil de classe",
      "Un bilan réalisé par un spécialiste mettant en évidence le trouble des apprentissages",
    ],
    bonne: 3,
    explication: "Un accompagnement personnalisé ne se met pas en place sur une simple demande : la famille doit apporter le bilan d'un spécialiste qui montre l'existence du trouble.",
    articles: [
      "3.1.3",
    ],
    citation: "Les élèves à besoins particulier peuvent bénéficier de la mise en place d’un accompagnement spécifique, sur production d’un bilan réalisé par un spécialiste mettant en évidence l’existence d’un trouble des apprentissages .",
    public: "parents",
    difficulte: "difficile",
  },
  {
    id: "communication-reunion-en-personne",
    theme: "communication",
    question: "Les deux parents sont empêchés le soir de la réunion parents-professeurs : ils envoient un proche à leur place. Est-ce accepté ?",
    type: "vrai-faux",
    options: [
      "Vrai",
      "Faux",
    ],
    bonne: 1,
    explication: "Au moins l'un des deux parents doit venir en personne à la réunion. Personne d'autre ne peut venir les représenter, même avec leur accord.",
    articles: [
      "3.1.2",
    ],
    citation: "L’un des deux parents, au moins, devra se présenter aux réunions en personne. En aucun cas, il ne pourra se faire représenter par une tierce personne.",
    public: "parents",
    difficulte: "moyenne",
  },
  {
    id: "materiel-securite-degradation-mobilier",
    theme: "materiel-securite",
    question: "Un élève dégrade une chaise de sa salle de classe. Qui règle les frais de réparation ?",
    type: "qcm",
    options: [
      "Sa famille règle le montant des frais de dégradation.",
      "L'établissement prend la réparation entièrement à sa charge.",
      "L'assurance scolaire rembourse automatiquement le mobilier abîmé.",
      "Toute la classe partage le coût de la réparation.",
    ],
    bonne: 0,
    explication: "Les locaux et le mobilier sont mis à la disposition de tous : ce qui est abîmé doit être réparé, et c'est la famille de l'élève qui en paie le coût.",
    articles: [
      "4.6",
    ],
    citation: "Toute dégradation devra être réparée. Les familles des élèves auront à régler le montant des frais de dégradation.",
    public: "les-deux",
    difficulte: "facile",
  },
  {
    id: "materiel-securite-parent-accueil",
    theme: "materiel-securite",
    question: "Un parent vient rencontrer un professeur. Comment entre-t-il dans l'établissement ?",
    type: "qcm",
    options: [
      "Il se présente à l'accueil et reçoit un badge visiteur ; l'accès se fait sur rendez-vous.",
      "Il entre par la porte principale et monte directement à la salle du professeur.",
      "Il attend son enfant dans la cour pendant la récréation.",
      "Il appelle le professeur depuis le portail pour qu'il vienne le chercher.",
    ],
    bonne: 0,
    explication: "Toute personne qui n'appartient pas à l'établissement passe d'abord par l'accueil, signale sa présence et porte un badge visiteur ; pour voir un professeur, il faut avoir pris rendez-vous.",
    articles: [
      "6.2",
    ],
    citation: "6.2. Personnes extérieures à l’établissement, parents d’élèves : entrées et sorties, déplacements dans l’établissement Toute personne extérieure à l’établissement doit se présenter à l’accueil afin d’informer de sa présence et d’être dirigée vers son interlocuteur. Un badge visiteur lui sera remis. En particulier, l’accès des parents à l’établissement se fait sur rendez-vous.",
    public: "parents",
    difficulte: "facile",
  },
  {
    id: "interdits-boissons-energisantes",
    theme: "interdits",
    question: "À la récréation, un élève sort de son sac une canette de soda et une boisson énergisante. Que dit le règlement ?",
    type: "qcm",
    options: [
      "C'est autorisé pendant les récréations, dans la cour",
      "C'est interdit : ces boissons n'ont pas leur place dans l'établissement",
      "C'est autorisé si la boisson est consommée hors des salles de classe",
      "C'est autorisé au lycée, mais interdit au collège",
    ],
    bonne: 1,
    explication: "Les sodas sucrés et les boissons énergisantes sont interdits partout dans l'établissement, pour des raisons de santé. Prévois plutôt une gourde ou une bouteille d'eau.",
    articles: [
      "4.7",
    ],
    citation: "Il est interdit de fumer dans l'établissement et ses abords. Il est aussi interdit d'y introduire, détenir ou consommer toute substance illicite ou boisson alcoolisée. Enfin pour des raisons de santé, les boissons gazeuses sucrées et/ou énergisantes sont strictement interdites.",
    public: "eleves",
    difficulte: "facile",
  },
  {
    id: "interdits-arme-factice",
    theme: "interdits",
    question: "Pour une journée déguisée, un élève veut apporter un pistolet en plastique qui complète son costume. Peut-il le faire ?",
    type: "qcm",
    options: [
      "Oui, s'il est visible que l'objet est un jouet",
      "Oui, avec une autorisation écrite de ses parents",
      "Non : même factice, une arme est interdite dans l'établissement",
      "Oui, s'il le laisse à la vie scolaire pendant les heures de cours",
    ],
    bonne: 2,
    explication: "Aucun objet dangereux ou sans rapport avec le travail scolaire n'entre dans l'établissement, et une arme de déguisement est expressément visée : elle reste interdite même si elle est fausse.",
    articles: [
      "4.7",
    ],
    citation: "Pour des raisons de sécurité, la détention de tout produit ou objet dangereux ou étranger à la pratique scolaire est prohibée y compris une arme factice destinée à un déguisement.",
    public: "eleves",
    difficulte: "difficile",
  },
  {
    id: "interdits-fumer-abords",
    theme: "interdits",
    question: "Un lycéen fume une cigarette sur le trottoir, juste devant le portail, avant d'entrer. Il respecte le règlement.",
    type: "vrai-faux",
    options: [
      "Vrai",
      "Faux",
    ],
    bonne: 1,
    explication: "L'interdiction de fumer ne s'arrête pas au portail : elle vaut aussi juste devant l'établissement, sur ses abords immédiats.",
    articles: [
      "4.7",
    ],
    citation: "Il est interdit de fumer dans l'établissement et ses abords.",
    public: "eleves",
    difficulte: "difficile",
  },
];
